// <auto-generated />
using Dictionarythesaurus.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dictionarythesaurus.Migrations
{
    [DbContext(typeof(DictionarythesaurusContext))]
    [Migration("20220823181725_AddedPartOfSpeech")]
    partial class AddedPartOfSpeech
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Dictionarythesaurus.Models.Antonyms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DictionaryId")
                        .HasColumnType("int");

                    b.Property<string>("WordAntonyms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DictionaryId");

                    b.ToTable("Antonyms");
                });

            modelBuilder.Entity("Dictionarythesaurus.Models.Definition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DictionaryId")
                        .HasColumnType("int");

                    b.Property<string>("PartOfSpeech")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WordDefinition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DictionaryId");

                    b.ToTable("Definition");
                });

            modelBuilder.Entity("Dictionarythesaurus.Models.Dictionary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dictionary");
                });

            modelBuilder.Entity("Dictionarythesaurus.Models.Synonyms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DictionaryId")
                        .HasColumnType("int");

                    b.Property<string>("WordSynonyms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DictionaryId");

                    b.ToTable("Synonyms");
                });

            modelBuilder.Entity("Dictionarythesaurus.Models.Antonyms", b =>
                {
                    b.HasOne("Dictionarythesaurus.Models.Dictionary", "Dictionary")
                        .WithMany("Antonyms")
                        .HasForeignKey("DictionaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dictionary");
                });

            modelBuilder.Entity("Dictionarythesaurus.Models.Definition", b =>
                {
                    b.HasOne("Dictionarythesaurus.Models.Dictionary", "Dictionary")
                        .WithMany("Definitions")
                        .HasForeignKey("DictionaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dictionary");
                });

            modelBuilder.Entity("Dictionarythesaurus.Models.Synonyms", b =>
                {
                    b.HasOne("Dictionarythesaurus.Models.Dictionary", "Dictionary")
                        .WithMany("Synonyms")
                        .HasForeignKey("DictionaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dictionary");
                });

            modelBuilder.Entity("Dictionarythesaurus.Models.Dictionary", b =>
                {
                    b.Navigation("Antonyms");

                    b.Navigation("Definitions");

                    b.Navigation("Synonyms");
                });
#pragma warning restore 612, 618
        }
    }
}
